### ISSUE TITLE
Missing implementation error

### ISSUE THREAD

**Issue by Tarunvegi-dev** [robrichardson13/flutter_aws_polly#2]
I am trying to work with this package to integrate the AWS Polly service, but the error not letting me do.

Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel aws_polly)

**Comment by robrichardson13** [comment]
Hi @Tarunvegi-dev, Android implementation has been added via PR https://github.com/robrichardson13/flutter_aws_polly/pull/4.

Just include with `aws_polly: ^2.0.0`.
